# -*- coding: utf-8 -*-
"""CA 2 BDA PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9XDvt2JCrNFdntczHUQwKGDsyFrknbj

PROBLEM STATEMENT

Urban crime analysis is challenging due to large, complex, and inconsistent crime datasets. This project uses Big Data Analytics and Machine Learning to analyze Chennai crime data, identify patterns, and classify crime incidents into risk levels (Low, Medium, High) to support proactive decision-making and public safety.
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import date_format,col,sum,when,count
from pyspark.sql.functions import year
from pyspark.sql.functions import month
from pyspark.sql.functions import mean
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

spark=SparkSession.builder.appName("Chennai Crime rate").getOrCreate()
df=spark.read.csv("/content/chennai_crime_realistic.csv",header=True,inferSchema=True)
df.show(5)

print(df.rdd.getNumPartitions())

"""**BASIC CHECKS**"""

df.printSchema()

df=df.drop('Data_Source')

df.show(1)

df.count()

df.columns

df.select([sum(col(c).isNull().cast("int")).alias(c)for c in df.columns]).show()

df.count() - df.dropDuplicates().count()

"""**DATA PREPROCESSING**"""

#handling missing values

age_mean = df.select(mean("Victim_Age")).first()[0]
df = df.fillna({"Victim_Age": age_mean})

area= df.groupBy("Area_in_Chennai").count().orderBy(col("count").desc()).first()[0]

gender= df.groupBy("Gender").count().orderBy(col("count").desc()).first()[0]

weapon= df.groupBy("Weapon_Used").count().orderBy(col("count").desc()).first()[0]

df = df.fillna({"Area_in_Chennai": area,"Gender": gender,"Weapon_Used": weapon})

df.select([sum(col(c).isNull().cast("int")).alias(c)for c in df.columns]).show()

"""**Feature engineering**"""

df=df.withColumn('Time',date_format(col('Time'),'HH:mm'))
df.show(2)

df = df.withColumn("Year", year("Date"))
df.show(1)

df = df.withColumn("Month", month("Date"))
df.show(1)

df = df.select("Area_in_Chennai", "Victim_Age", "Gender", "Type_of_Crime","Date","Time","Hour","Year","Month","Weapon_Used")
df.show(1)

df.createOrReplaceTempView("crime_data")
spark.sql('''select Type_of_Crime, COUNT(*) as count from crime_data group by Type_of_Crime''').show()
spark.sql('''select Weapon_Used, COUNT(*) as count from crime_data group by Weapon_Used''').show()

from pyspark.sql.functions import when, col

df = df.withColumn("Risk_Level",
    when(
        col("Type_of_Crime").isin("Murder", "Kidnapping") |
        (col("Type_of_Crime").isin("Sexual Harassment", "Assault", "Robbery") &
            col("Weapon_Used").isin("Gun", "Knife", "Acid")
        ) |(col("Type_of_Crime").isin("Robbery", "Assault") &(col("Hour") >= 22)),"High")

    .when(
        col("Type_of_Crime").isin(
            "Sexual Harassment", "Assault", "Robbery", "Theft", "Cheating"
        ) |
        (col("Weapon_Used").isin("Iron Rod", "Stick", "Blade", "Rope")),"Medium")

    .otherwise("Low"))

df.show(5)

df.createOrReplaceTempView("crime_data")
spark.sql('''select Risk_Level, COUNT(*) as count from crime_data group by Risk_Level''').show()

df.show(2)

data=df.select('Area_in_Chennai','Victim_Age','Gender','Type_of_Crime','Date','Time','Hour','Year','Month','Weapon_Used','Risk_Level').toPandas()

data.head()

import plotly.express as px

crimerisk=px.histogram(data,x='Risk_Level',color='Risk_Level',title='Crime Risk Level Distribution')
crimerisk.show()

"""shows the distribution of crime risk levels. Medium risk crimes occur most frequently, followed by low risk and high risk crimes. The plot helps identify class imbalance"""

#area wise crime risk

area=data.groupby(['Area_in_Chennai','Risk_Level']).size().reset_index(name='Count')
arearisk=px.bar(area,x='Area_in_Chennai',y='Count',color='Risk_Level',title='Area wise Risk Level',barmode='stack')
arearisk.show()

"""shows area wise crime distribution by risk level  highlighting that medium risk crimes dominate across Chennai while areas like T Nagar and Velachery shows higher overall crime intensity."""

#time

hour = data.groupby("Hour").size().reset_index(name="Count")
hr = px.line(hour,x="Hour",y="Count",markers=True,title="Crime Occurrence by Hour of Day")
hr.show()

"""1. Low crime during early morning

Between 12 AM to  5 AM, crime count is relatively low


 2. Sudden rise after morning

Around 6 AM to 10 AM, crime increases

Matches office hours, school hours, public travel

3. High crime during evening & night

6 PM to 10 PM shows the highest crime rate

Heavy crowd movement
Higher chance of robbery & assault


4. Late night remains risky

Crime stays high even after 8 PM

Suggests need for extra police patrolling at night
"""

monthly = data.groupby("Month").size().reset_index(name="Count")
month_crime = px.line(monthly,x="Month",y="Count",markers=True,title="Monthly Crime Trend")
month_crime.show()

"""This plot shows the monthly crime trend indicating that crime occurs consistently throughout the year with small fluctuations, helping identify months with higher risk"""

year = data.groupby("Year").size().reset_index(name="Count")
yr = px.line(year,x="Year",y="Count",markers=True,title="Year Crime Trend")
yr.show()

crime_risk = data.groupby(["Type_of_Crime", "Risk_Level"]).size().reset_index(name="Count")

crimetype = px.bar(crime_risk,x="Type_of_Crime",y="Count",color="Risk_Level",title="Crime Type vs Risk Level",barmode="group")

crimetype.show()

"""This compares crime types with their risk levels and shows that violent crimes contribute more to high risk while cyber and theft crimes are mostly medium or low risk."""

area_hr=data.groupby(["Area_in_Chennai",'Hour']).size().reset_index(name='count')
areahr = px.bar(area_hr,x="Hour",y="count",color="Area_in_Chennai",title="Hour wise Crime by Area",barmode="stack")
areahr.show()

"""Crime is lowest during early morning hours (0–5 AM) across all areas.

Sharp increase after morning (6 AM),

Peak crime hours are evening to night (6 PM–10 PM) in most areas.

T Nagar, Tambaram, Velachery show higher crime counts at peak hours.
"""

spark.sql(''' select Type_of_Crime,Risk_Level,count(*) AS Count from crime_data group by Type_of_Crime,
 Risk_Level order by Type_of_Crime, Risk_Level''').show()

spark.sql('''select Area_in_Chennai,Type_of_Crime,count(*) as Count FROM crime_data group by Area_in_Chennai,
 Type_of_Crime order by Area_in_Chennai, Type_of_Crime''').show(100)

df.groupBy("Risk_Level").count().show()

from pyspark.sql.functions import col

high_df = df.filter(col("Risk_Level") == "High")
low_df = df.filter(col("Risk_Level") == "Low")
medium_df = df.filter(col("Risk_Level") == "Medium")

medium_sample = medium_df.sample(fraction=0.3, seed=42)

balanced_df = high_df.union(low_df).union(medium_sample)

balanced_df.groupBy("Risk_Level").count().show()

high_df = df.filter(col("Risk_Level") == "High")
low_df = df.filter(col("Risk_Level") == "Low")
medium_df = df.filter(col("Risk_Level") == "Medium")

high_oversampled = high_df.sample(withReplacement=True, fraction=2.5, seed=42)
low_oversampled = low_df.sample(withReplacement=True, fraction=2.5, seed=42)

balanced_df = high_oversampled.union(low_oversampled).union(medium_df)

balanced_df.groupBy("Risk_Level").count().show()

fractions = {
    "High": 1.0,
    "Low": 1.0,
    "Medium": 0.3
}

balanced_df = df.sampleBy("Risk_Level", fractions, seed=42)

balanced_df.groupBy("Risk_Level").count().show()



spark.sql('''select Gender,Type_of_Crime,count(*) as count
from crime_data group by Gender, Type_of_Crime order by Type_of_Crime, Gender''').show()

risk_encoding=StringIndexer(inputCol='Risk_Level',outputCol='Risk_index')

area_indexer   = StringIndexer(inputCol="Area_in_Chennai", outputCol="Area_Index")
gender_indexer = StringIndexer(inputCol="Gender", outputCol="Gender_Index")
weapon_indexer = StringIndexer(inputCol="Weapon_Used", outputCol="Weapon_Index")
crime_indexer  = StringIndexer(inputCol="Type_of_Crime", outputCol="Crime_Index")

df_indexed = area_indexer.fit(df).transform(df)
df_indexed = gender_indexer.fit(df_indexed).transform(df_indexed)
df_indexed = weapon_indexer.fit(df_indexed).transform(df_indexed)
df_indexed = crime_indexer.fit(df_indexed).transform(df_indexed)

df_indexed = risk_encoding.fit(df_indexed).transform(df_indexed)

assembler = VectorAssembler(inputCols=["Area_Index","Gender_Index","Crime_Index","Victim_Age","Hour","Month"],outputCol="features")

df_model = assembler.transform(df_indexed)

df_model=df_model.drop('prediction')

train, test = df_model.randomSplit([0.8,0.2], seed=42)

train, test = balanced_df.randomSplit([0.8,0.2], seed=42)

balanced_df.groupBy("Risk_Level").count().show()

evaluator = MulticlassClassificationEvaluator(labelCol="Risk_index",predictionCol="prediction",metricName="accuracy")

"""#risk level prediction

"""

from pyspark.ml.classification import LogisticRegression

lr = LogisticRegression(labelCol="Risk_index",featuresCol="features")


lr_model=lr.fit(train)
train_pred = lr_model.transform(train)
train_acc = evaluator.evaluate(train_pred)
print("Train Accuracy:", train_acc)

test_pred = lr_model.transform(test)
test_acc = evaluator.evaluate(test_pred)
print("Test Accuracy:", test_acc)

from pyspark.ml.classification import DecisionTreeClassifier

dt = DecisionTreeClassifier(labelCol="Risk_index",featuresCol="features",maxDepth=5)

dt_model = dt.fit(train)

dt_train_pred = dt_model.transform(train)
dt_train_acc = evaluator.evaluate(dt_train_pred)
print("Decision Tree Train Accuracy:", dt_train_acc)

dt_test_pred = dt_model.transform(test)
dt_test_acc = evaluator.evaluate(dt_test_pred)
print("Decision Tree Test Accuracy:", dt_test_acc)

from pyspark.ml.classification import NaiveBayes

nb = NaiveBayes(labelCol="Risk_index", featuresCol="features")

nb_model = nb.fit(train)

train_pred = nb_model.transform(train)
train_acc = evaluator.evaluate(train_pred)
print("NB Train Accuracy:", train_acc)

test_pred = nb_model.transform(test)
test_acc = evaluator.evaluate(test_pred)
print("NB Test Accuracy:", test_acc)

from pyspark.ml.classification import LinearSVC
from pyspark.ml.classification import OneVsRest

svm = LinearSVC(labelCol="Risk_index", featuresCol="features")

ovr = OneVsRest(classifier=svm, labelCol="Risk_index", featuresCol="features")

svm_model = ovr.fit(train)

train_pred = svm_model.transform(train)
train_acc = evaluator.evaluate(train_pred)
print("SVM Train Accuracy:", train_acc)

test_pred = svm_model.transform(test)
test_acc = evaluator.evaluate(test_pred)
print("SVM Test Accuracy:", test_acc)

lr_train_pred = lr_model.transform(train)
lr_train_acc = evaluator.evaluate(lr_train_pred)
lr_test_pred = lr_model.transform(test)
lr_test_acc = evaluator.evaluate(lr_test_pred)


dt_train_pred = dt_model.transform(train)
dt_train_acc = evaluator.evaluate(dt_train_pred)
dt_test_pred = dt_model.transform(test)
dt_test_acc = evaluator.evaluate(dt_test_pred)


nb_train_pred = nb_model.transform(train)
nb_train_acc = evaluator.evaluate(nb_train_pred)
nb_test_pred = nb_model.transform(test)
nb_test_acc = evaluator.evaluate(nb_test_pred)


svm_train_pred = svm_model.transform(train)
svm_train_acc = evaluator.evaluate(svm_train_pred)
svm_test_pred = svm_model.transform(test)
svm_test_acc = evaluator.evaluate(svm_test_pred)


print("Model Comparison")
print("------------------------------------")
print("Logistic Regression Train:", lr_train_acc)
print("Logistic Regression Test :", lr_test_acc)

print("Decision Tree Train:", dt_train_acc)
print("Decision Tree Test :", dt_test_acc)

print("Naive Bayes Train:", nb_train_acc)
print("Naive Bayes Test :", nb_test_acc)

print("SVM Train:", svm_train_acc)
print("SVM Test :", svm_test_acc)



new_data = spark.createDataFrame([(3.0, 1.0, 5.0, 24.0, 22.0, 7.0)],
["Area_Index", "Gender_Index", "Crime_Index", "Victim_Age", "Hour", "Month"])

new_data_features = assembler.transform(new_data)
prediction = dt_model.transform(new_data_features)
prediction.select("prediction", "probability").show(truncate=False)

dt_test_pred.groupBy("Risk_index", "prediction").count().show()

"""#clustering based on similarites

"""

from pyspark.ml.clustering import KMeans

kmeans = KMeans(k=4, seed=42, featuresCol="features")

model = kmeans.fit(df_model)

result = model.transform(df_model)

result.select("Area_in_Chennai","Type_of_Crime","prediction").show()

result.show()

result.groupBy("prediction","Area_in_Chennai").count().show()

result.groupBy("prediction","Hour").count().show()

result.groupBy("prediction","Victim_Age").count().show()

"""Cluster 0 -theft & kidnapping crimes in certain areas

Cluster 1 - robbery and cyber crimes pattern

Cluster 2 - assault and theft crimes with similar victim age

Cluster 3 - mixed crimes happening at similar time periods
"""

dt_model.write().overwrite().save("decision_tree_model")

#import shutil
#shutil.make_archive("decision_tree_model", 'zip', "decision_tree_model")

#from google.colab import files
#files.download("decision_tree_model.zip")

pdf = df_indexed.toPandas()

X = pdf[["Area_Index","Gender_Index","Crime_Index","Victim_Age","Hour"]]

y = pdf["Risk_Level"]

from sklearn.tree import DecisionTreeClassifier
import pickle

model = DecisionTreeClassifier()
model.fit(X, y)

with open("crime_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("PKL file created successfully")

